server:
    port: 8080


### spring ############################################################
spring:
    datasource:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@sunja.asuscomm.com:1521/xe
        username: CHOROK
        password: tower0814

    banner:
        location: banner_account.txt    